name: Go Build and Release

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.26'

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: ~/.cache/go-build
          key: ${{ runner.os }}-go-mod-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-mod-

      - name: Install dependencies
        run: go mod tidy

      - name: Build Linux binary
        run: GOARCH=amd64 GOOS=linux go build -o splashchanger-linux-amd64

      - name: Create Release and Upload Assets
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: splashchanger-linux-amd64

      - name: Add release description
        run: |
          RELEASE_TAG="${GITHUB_REF#refs/tags/}"
          curl -s -X PATCH \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -d "{\"body\":\"Release ${RELEASE_TAG} of splashchanger. See the binary attached.\"}" \
            "https://api.github.com/repos/${{ github.repository }}/releases/tags/${RELEASE_TAG}"
